Metatavu/vp-kuljetus-transport-management-charts

charts/transport-management/Chart.yaml, charts/transport-management/charts/auth/Chart.yaml, charts/transport-management/charts/auth/templates/auth-deployment.yaml, charts/transport-management/charts/auth/values.yaml, charts/transport-management/charts/tyk-redis/Chart.yaml, charts/transport-management/charts/vehicle-data-receiver/.helmignore, charts/transport-management/charts/vehicle-data-receiver/Chart.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-deployment.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-service.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml
=> Helm chart for VP-Kuljetus Vehicle Data Receiver

charts/transport-management/charts/auth/values.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-deployment.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml
- Also increased Keycloak probe delays
=> Configured infisical for Vehicle Data Receiver

.github/workflows/develop-release-charts.yaml, .github/workflows/master-release-charts.yaml, charts/transport-management/Chart.yaml, charts/transport-management/charts/auth/Chart.yaml, charts/transport-management/charts/tyk-gateway/Chart.yaml, charts/transport-management/charts/tyk-redis/Chart.yaml, charts/transport-management/charts/vehicle-data-receiver/Chart.yaml, charts/transport-management/charts/vehicle-management-service/Chart.yaml, charts/transport-management/charts/work-planning-service/.helmignore, charts/transport-management/charts/work-planning-service/Chart.yaml, charts/transport-management/charts/work-planning-service/templates/vehicle-management-service-deployment.yaml, charts/transport-management/charts/work-planning-service/templates/vehicle-management-service-service.yaml, charts/transport-management/charts/work-planning-service/values.yaml
=> Added work planning services api chart

.github/workflows/develop-release-charts.yaml, .github/workflows/master-release-charts.yaml, charts/transport-management/Chart.yaml, charts/transport-management/charts/auth/Chart.yaml, charts/transport-management/charts/delivery-info-service/.helmignore, charts/transport-management/charts/delivery-info-service/Chart.yaml, charts/transport-management/charts/delivery-info-service/templates/vehicle-management-service-deployment.yaml, charts/transport-management/charts/delivery-info-service/templates/vehicle-management-service-service.yaml, charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/tyk-gateway/Chart.yaml, charts/transport-management/charts/tyk-gateway/templates/tyk-gateway-apps-configmap.yaml, charts/transport-management/charts/tyk-redis/Chart.yaml, charts/transport-management/charts/vehicle-data-receiver/Chart.yaml, charts/transport-management/charts/vehicle-management-service/Chart.yaml, charts/transport-management/charts/work-planning-service/Chart.yaml
=> Feature 20 add delivery info service api chart

.github/workflows/develop-release-charts.yaml, charts/transport-management/charts/auth/templates/auth-deployment.yaml, charts/transport-management/charts/auth/values.yaml
=> Feature 27 keycloak automatic deployment

charts/transport-management/charts/delivery-info-service/templates/delivery-info-service-deployment.yaml, charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/user-management-service/templates/user-management-service-deployment.yaml, charts/transport-management/charts/user-management-service/values.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-deployment.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml, charts/transport-management/charts/vehicle-management-service/templates/vehicle-management-service-deployment.yaml, charts/transport-management/charts/vehicle-management-service/values.yaml, charts/transport-management/charts/work-planning-service/templates/work-planning-service-deployment.yaml, charts/transport-management/charts/work-planning-service/values.yaml
=> Added default resources to all deployments

charts/transport-management/charts/delivery-info-service/templates/delivery-info-service-deployment.yaml, charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/user-management-service/templates/user-management-service-deployment.yaml, charts/transport-management/charts/user-management-service/values.yaml, charts/transport-management/charts/vehicle-management-service/templates/vehicle-management-service-deployment.yaml, charts/transport-management/charts/vehicle-management-service/values.yaml, charts/transport-management/charts/work-planning-service/templates/work-planning-service-deployment.yaml, charts/transport-management/charts/work-planning-service/values.yaml
=> Feature 38 quarkus health checks

charts/transport-management/charts/delivery-info-service/templates/delivery-info-service-deployment.yaml
=> Fixed invalid probes on delivery info service

charts/transport-management/charts/delivery-info-service/templates/delivery-info-service-deployment.yaml, charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/user-management-service/templates/user-management-service-deployment.yaml, charts/transport-management/charts/user-management-service/values.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml, charts/transport-management/charts/vehicle-management-service/templates/vehicle-management-service-deployment.yaml, charts/transport-management/charts/vehicle-management-service/values.yaml, charts/transport-management/charts/work-planning-service/templates/work-planning-service-deployment.yaml, charts/transport-management/charts/work-planning-service/values.yaml
=> Fixed issue #42

charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/user-management-service/values.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml, charts/transport-management/charts/vehicle-management-service/values.yaml, charts/transport-management/charts/work-planning-service/values.yaml
=> Changed failureThreshold to 1 and all readiness probes

.github/workflows/develop-release-charts.yaml, README.md, charts/transport-management/charts/rabbitmq/.helmignore, charts/transport-management/charts/rabbitmq/Chart.yaml, charts/transport-management/charts/rabbitmq/rabbitmq-cluster.yaml, charts/transport-management/charts/rabbitmq/values.yaml, charts/transport-management/templates/ingress.yaml, charts/transport-management/values.yaml
=> Feature 48 rabbitmq

.github/workflows/develop-release-charts.yaml, charts/transport-management/templates/ingress.yaml
=> Included rabbit chart to a main chart

.github/workflows/develop-release-charts.yaml, charts/transport-management/charts/auth/templates/auth-secret.yaml, charts/transport-management/charts/delivery-info-service/templates/delivery-info-service-secret.yaml, charts/transport-management/charts/user-management-service/templates/user-management-service-secret.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-secret.yaml, charts/transport-management/charts/vehicle-management-service/templates/vehicle-management-service-secret.yaml, charts/transport-management/charts/work-planning-service/templates/work-planning-service-secret.yaml, charts/transport-management/templates/secret-store.yaml, charts/transport-management/values.yaml
=> Added external secrets

charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-deployment.yaml, charts/transport-management/charts/vehicle-data-receiver/templates/vehicle-data-receiver-service.yaml
=> Ports for different devices

charts/transport-management/charts/tyk-gateway/templates/tyk-gateway-apps-configmap.yaml
=> Monitoring gateway

charts/transport-management/charts/tyk-gateway/templates/tyk-gateway-apps-configmap.yaml
Reverts Metatavu/vp-kuljetus-transport-management-charts#79
=> Revert "Monitoring gateway"

charts/transport-management/charts/monitoring-service/templates/cronjob.yaml, charts/transport-management/charts/user-management-service/templates/cronjob.yaml
=> Feature 87 incident cron jobs

.github/workflows/master-release-charts.yaml, charts/transport-management/charts/vehicle-data-receiver/values.yaml
- increased data receiver resources
- fixed production workflow
=> Production update 23.5.2025 #2

.github/workflows/dispatch-and-await-remote-build.yaml, .github/workflows/master-release-charts.yaml, charts/transport-management/Chart.yaml, charts/transport-management/charts/auth/Chart.yaml, charts/transport-management/charts/auth/values.yaml, charts/transport-management/charts/delivery-info-service/Chart.yaml, charts/transport-management/charts/delivery-info-service/values.yaml, charts/transport-management/charts/monitoring-service/values.yaml, charts/transport-management/charts/tyk-gateway/Chart.yaml, charts/transport-management/charts/tyk-redis/Chart.yaml, charts/transport-management/charts/user-management-service/Chart.yaml, charts/transport-management/charts/user-management-service/values.yaml, charts/transport-management/charts/vehicle-data-receiver/Chart.yaml, charts/transport-management/charts/vehicle-management-service/Chart.yaml, charts/transport-management/charts/work-planning-service/Chart.yaml
- split master release remote build steps to separate reusable workflow
=> Production update 9.6.2025 #6

.github/workflows/dispatch-and-await-remote-build.yaml
- defined reusable workflow secrets
=> Production update 9.6.2025 #7

.github/workflows/dispatch-and-await-remote-build.yaml, .github/workflows/master-release-charts.yaml
- changed workflow name to be input for reusable workflow
=> Production update 9.6.2025 #9
